syntax = "proto3";

package distbuild;

/*
  Common data types
*/
message FileInfo {
  string filename = 1;
  uint64 filesize = 2;
  bytes filehash = 3;
}

/*
  Client messages
*/
message ClientMessage {
  oneof content {
    ClientSessionStartRequest session_start = 1;
    ClientSessionAbortRequest session_abort = 2;
    ClientFileChunkUploadRequest file_chunk_upload = 3;
  }
}

message ClientSessionStartRequest {
  string client_id = 1;
  string client_working_dir = 2;
  string client_source_file = 3;
  string client_compiler = 4;
  repeated string client_cmd_line_args = 5;
  repeated string client_idirs = 6;
  repeated FileInfo required_files_info = 7;
}

message ClientSessionAbortRequest {
  string session_id = 1;
  string client_id = 2;
}

message ClientFileChunkUploadRequest {
  string session_id = 1;
  string filename = 2;
  uint64 sequence_no = 3;
  uint64 offset = 4;
  bytes data = 5;
  bool is_last_chunk = 6;
}

/*
  Server messages
*/
message ServerMessage {
  oneof content {
    ServerSessionConfirmedResponse session_confirmed = 1;
    ServerSessionAbortResponse session_abort = 2;
    ServerFileUpCompleteResponse file_up_complete = 3;
    ServerAllReqUploadCompleteResponse all_req_up_complete = 4;
    ServerObjFileChunkResponse obj_file_chunk_transmit = 5;
  }
}

message ServerSessionConfirmedResponse {
  string session_id = 1;
  repeated string required_files = 2;
}

message ServerSessionAbortResponse {
  string session_id = 1;
  string client_id = 2;
}

message ServerFileUpCompleteResponse {
  string session_id = 1;
  string filename = 2;
  bool success = 3;
}

message ServerAllReqUploadCompleteResponse {
  string session_id = 1;
}

message ServerObjFileChunkResponse {
  string session_id = 1;
  int32 compiler_exit_code = 2;
  int32 compiler_call_duration = 3;
  string compiler_stdout = 4;
  string compiler_stderr = 5;
  uint64 filesize = 6;
  bool is_last_chunk = 7;
  bytes data = 8;
}

