# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/radu/distbuild/DistBuildSys

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/radu/distbuild/DistBuildSys

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/radu/distbuild/DistBuildSys/CMakeFiles /home/radu/distbuild/DistBuildSys//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/radu/distbuild/DistBuildSys/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named distbuild_wrapper

# Build rule for target.
distbuild_wrapper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 distbuild_wrapper
.PHONY : distbuild_wrapper

# fast build rule for target.
distbuild_wrapper/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distbuild_wrapper.dir/build.make CMakeFiles/distbuild_wrapper.dir/build
.PHONY : distbuild_wrapper/fast

#=============================================================================
# Target rules for targets named distbuild_daemon

# Build rule for target.
distbuild_daemon: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 distbuild_daemon
.PHONY : distbuild_daemon

# fast build rule for target.
distbuild_daemon/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distbuild_daemon.dir/build.make CMakeFiles/distbuild_daemon.dir/build
.PHONY : distbuild_daemon/fast

src/compiler_wrapper_main.o: src/compiler_wrapper_main.cpp.o
.PHONY : src/compiler_wrapper_main.o

# target to build an object file
src/compiler_wrapper_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distbuild_wrapper.dir/build.make CMakeFiles/distbuild_wrapper.dir/src/compiler_wrapper_main.cpp.o
.PHONY : src/compiler_wrapper_main.cpp.o

src/compiler_wrapper_main.i: src/compiler_wrapper_main.cpp.i
.PHONY : src/compiler_wrapper_main.i

# target to preprocess a source file
src/compiler_wrapper_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distbuild_wrapper.dir/build.make CMakeFiles/distbuild_wrapper.dir/src/compiler_wrapper_main.cpp.i
.PHONY : src/compiler_wrapper_main.cpp.i

src/compiler_wrapper_main.s: src/compiler_wrapper_main.cpp.s
.PHONY : src/compiler_wrapper_main.s

# target to generate assembly for a file
src/compiler_wrapper_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distbuild_wrapper.dir/build.make CMakeFiles/distbuild_wrapper.dir/src/compiler_wrapper_main.cpp.s
.PHONY : src/compiler_wrapper_main.cpp.s

src/daemon_main.o: src/daemon_main.cpp.o
.PHONY : src/daemon_main.o

# target to build an object file
src/daemon_main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distbuild_daemon.dir/build.make CMakeFiles/distbuild_daemon.dir/src/daemon_main.cpp.o
.PHONY : src/daemon_main.cpp.o

src/daemon_main.i: src/daemon_main.cpp.i
.PHONY : src/daemon_main.i

# target to preprocess a source file
src/daemon_main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distbuild_daemon.dir/build.make CMakeFiles/distbuild_daemon.dir/src/daemon_main.cpp.i
.PHONY : src/daemon_main.cpp.i

src/daemon_main.s: src/daemon_main.cpp.s
.PHONY : src/daemon_main.s

# target to generate assembly for a file
src/daemon_main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distbuild_daemon.dir/build.make CMakeFiles/distbuild_daemon.dir/src/daemon_main.cpp.s
.PHONY : src/daemon_main.cpp.s

src/includes_rework.o: src/includes_rework.cpp.o
.PHONY : src/includes_rework.o

# target to build an object file
src/includes_rework.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distbuild_daemon.dir/build.make CMakeFiles/distbuild_daemon.dir/src/includes_rework.cpp.o
.PHONY : src/includes_rework.cpp.o

src/includes_rework.i: src/includes_rework.cpp.i
.PHONY : src/includes_rework.i

# target to preprocess a source file
src/includes_rework.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distbuild_daemon.dir/build.make CMakeFiles/distbuild_daemon.dir/src/includes_rework.cpp.i
.PHONY : src/includes_rework.cpp.i

src/includes_rework.s: src/includes_rework.cpp.s
.PHONY : src/includes_rework.s

# target to generate assembly for a file
src/includes_rework.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/distbuild_daemon.dir/build.make CMakeFiles/distbuild_daemon.dir/src/includes_rework.cpp.s
.PHONY : src/includes_rework.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... distbuild_daemon"
	@echo "... distbuild_wrapper"
	@echo "... src/compiler_wrapper_main.o"
	@echo "... src/compiler_wrapper_main.i"
	@echo "... src/compiler_wrapper_main.s"
	@echo "... src/daemon_main.o"
	@echo "... src/daemon_main.i"
	@echo "... src/daemon_main.s"
	@echo "... src/includes_rework.o"
	@echo "... src/includes_rework.i"
	@echo "... src/includes_rework.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

