// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: support/filetransfer_messages.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_support_2ffiletransfer_5fmessages_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_support_2ffiletransfer_5fmessages_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_support_2ffiletransfer_5fmessages_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_support_2ffiletransfer_5fmessages_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_support_2ffiletransfer_5fmessages_2eproto;
namespace filetransfer {
class ClientMessage;
class ClientMessageDefaultTypeInternal;
extern ClientMessageDefaultTypeInternal _ClientMessage_default_instance_;
class FileChunk;
class FileChunkDefaultTypeInternal;
extern FileChunkDefaultTypeInternal _FileChunk_default_instance_;
class FileTransferRequest;
class FileTransferRequestDefaultTypeInternal;
extern FileTransferRequestDefaultTypeInternal _FileTransferRequest_default_instance_;
class FileUploadFinished;
class FileUploadFinishedDefaultTypeInternal;
extern FileUploadFinishedDefaultTypeInternal _FileUploadFinished_default_instance_;
class FileUploadStatus;
class FileUploadStatusDefaultTypeInternal;
extern FileUploadStatusDefaultTypeInternal _FileUploadStatus_default_instance_;
class ServerMessage;
class ServerMessageDefaultTypeInternal;
extern ServerMessageDefaultTypeInternal _ServerMessage_default_instance_;
}  // namespace filetransfer
PROTOBUF_NAMESPACE_OPEN
template<> ::filetransfer::ClientMessage* Arena::CreateMaybeMessage<::filetransfer::ClientMessage>(Arena*);
template<> ::filetransfer::FileChunk* Arena::CreateMaybeMessage<::filetransfer::FileChunk>(Arena*);
template<> ::filetransfer::FileTransferRequest* Arena::CreateMaybeMessage<::filetransfer::FileTransferRequest>(Arena*);
template<> ::filetransfer::FileUploadFinished* Arena::CreateMaybeMessage<::filetransfer::FileUploadFinished>(Arena*);
template<> ::filetransfer::FileUploadStatus* Arena::CreateMaybeMessage<::filetransfer::FileUploadStatus>(Arena*);
template<> ::filetransfer::ServerMessage* Arena::CreateMaybeMessage<::filetransfer::ServerMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace filetransfer {

// ===================================================================

class ClientMessage PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:filetransfer.ClientMessage) */ {
 public:
  inline ClientMessage() : ClientMessage(nullptr) {};
  virtual ~ClientMessage();

  ClientMessage(const ClientMessage& from);
  ClientMessage(ClientMessage&& from) noexcept
    : ClientMessage() {
    *this = ::std::move(from);
  }

  inline ClientMessage& operator=(const ClientMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ClientMessage& operator=(ClientMessage&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ClientMessage& default_instance();

  enum ContentCase {
    kFileRequest = 1,
    kFileChunk = 2,
    kUploadFinished = 3,
    CONTENT_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ClientMessage* internal_default_instance() {
    return reinterpret_cast<const ClientMessage*>(
               &_ClientMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ClientMessage& a, ClientMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(ClientMessage* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ClientMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ClientMessage* New() const final {
    return CreateMaybeMessage<ClientMessage>(nullptr);
  }

  ClientMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ClientMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ClientMessage& from);
  void MergeFrom(const ClientMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ClientMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "filetransfer.ClientMessage";
  }
  protected:
  explicit ClientMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_support_2ffiletransfer_5fmessages_2eproto);
    return ::descriptor_table_support_2ffiletransfer_5fmessages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFileRequestFieldNumber = 1,
    kFileChunkFieldNumber = 2,
    kUploadFinishedFieldNumber = 3,
  };
  // .filetransfer.FileTransferRequest file_request = 1;
  bool has_file_request() const;
  private:
  bool _internal_has_file_request() const;
  public:
  void clear_file_request();
  const ::filetransfer::FileTransferRequest& file_request() const;
  ::filetransfer::FileTransferRequest* release_file_request();
  ::filetransfer::FileTransferRequest* mutable_file_request();
  void set_allocated_file_request(::filetransfer::FileTransferRequest* file_request);
  private:
  const ::filetransfer::FileTransferRequest& _internal_file_request() const;
  ::filetransfer::FileTransferRequest* _internal_mutable_file_request();
  public:
  void unsafe_arena_set_allocated_file_request(
      ::filetransfer::FileTransferRequest* file_request);
  ::filetransfer::FileTransferRequest* unsafe_arena_release_file_request();

  // .filetransfer.FileChunk file_chunk = 2;
  bool has_file_chunk() const;
  private:
  bool _internal_has_file_chunk() const;
  public:
  void clear_file_chunk();
  const ::filetransfer::FileChunk& file_chunk() const;
  ::filetransfer::FileChunk* release_file_chunk();
  ::filetransfer::FileChunk* mutable_file_chunk();
  void set_allocated_file_chunk(::filetransfer::FileChunk* file_chunk);
  private:
  const ::filetransfer::FileChunk& _internal_file_chunk() const;
  ::filetransfer::FileChunk* _internal_mutable_file_chunk();
  public:
  void unsafe_arena_set_allocated_file_chunk(
      ::filetransfer::FileChunk* file_chunk);
  ::filetransfer::FileChunk* unsafe_arena_release_file_chunk();

  // .filetransfer.FileUploadFinished upload_finished = 3;
  bool has_upload_finished() const;
  private:
  bool _internal_has_upload_finished() const;
  public:
  void clear_upload_finished();
  const ::filetransfer::FileUploadFinished& upload_finished() const;
  ::filetransfer::FileUploadFinished* release_upload_finished();
  ::filetransfer::FileUploadFinished* mutable_upload_finished();
  void set_allocated_upload_finished(::filetransfer::FileUploadFinished* upload_finished);
  private:
  const ::filetransfer::FileUploadFinished& _internal_upload_finished() const;
  ::filetransfer::FileUploadFinished* _internal_mutable_upload_finished();
  public:
  void unsafe_arena_set_allocated_upload_finished(
      ::filetransfer::FileUploadFinished* upload_finished);
  ::filetransfer::FileUploadFinished* unsafe_arena_release_upload_finished();

  void clear_content();
  ContentCase content_case() const;
  // @@protoc_insertion_point(class_scope:filetransfer.ClientMessage)
 private:
  class _Internal;
  void set_has_file_request();
  void set_has_file_chunk();
  void set_has_upload_finished();

  inline bool has_content() const;
  inline void clear_has_content();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  union ContentUnion {
    ContentUnion() {}
    ::filetransfer::FileTransferRequest* file_request_;
    ::filetransfer::FileChunk* file_chunk_;
    ::filetransfer::FileUploadFinished* upload_finished_;
  } content_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_support_2ffiletransfer_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class ServerMessage PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:filetransfer.ServerMessage) */ {
 public:
  inline ServerMessage() : ServerMessage(nullptr) {};
  virtual ~ServerMessage();

  ServerMessage(const ServerMessage& from);
  ServerMessage(ServerMessage&& from) noexcept
    : ServerMessage() {
    *this = ::std::move(from);
  }

  inline ServerMessage& operator=(const ServerMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ServerMessage& operator=(ServerMessage&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ServerMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ServerMessage* internal_default_instance() {
    return reinterpret_cast<const ServerMessage*>(
               &_ServerMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ServerMessage& a, ServerMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(ServerMessage* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ServerMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ServerMessage* New() const final {
    return CreateMaybeMessage<ServerMessage>(nullptr);
  }

  ServerMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ServerMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ServerMessage& from);
  void MergeFrom(const ServerMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ServerMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "filetransfer.ServerMessage";
  }
  protected:
  explicit ServerMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_support_2ffiletransfer_5fmessages_2eproto);
    return ::descriptor_table_support_2ffiletransfer_5fmessages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUploadStatusFieldNumber = 1,
  };
  // .filetransfer.FileUploadStatus upload_status = 1;
  bool has_upload_status() const;
  private:
  bool _internal_has_upload_status() const;
  public:
  void clear_upload_status();
  const ::filetransfer::FileUploadStatus& upload_status() const;
  ::filetransfer::FileUploadStatus* release_upload_status();
  ::filetransfer::FileUploadStatus* mutable_upload_status();
  void set_allocated_upload_status(::filetransfer::FileUploadStatus* upload_status);
  private:
  const ::filetransfer::FileUploadStatus& _internal_upload_status() const;
  ::filetransfer::FileUploadStatus* _internal_mutable_upload_status();
  public:
  void unsafe_arena_set_allocated_upload_status(
      ::filetransfer::FileUploadStatus* upload_status);
  ::filetransfer::FileUploadStatus* unsafe_arena_release_upload_status();

  // @@protoc_insertion_point(class_scope:filetransfer.ServerMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::filetransfer::FileUploadStatus* upload_status_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_support_2ffiletransfer_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class FileTransferRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:filetransfer.FileTransferRequest) */ {
 public:
  inline FileTransferRequest() : FileTransferRequest(nullptr) {};
  virtual ~FileTransferRequest();

  FileTransferRequest(const FileTransferRequest& from);
  FileTransferRequest(FileTransferRequest&& from) noexcept
    : FileTransferRequest() {
    *this = ::std::move(from);
  }

  inline FileTransferRequest& operator=(const FileTransferRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileTransferRequest& operator=(FileTransferRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FileTransferRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FileTransferRequest* internal_default_instance() {
    return reinterpret_cast<const FileTransferRequest*>(
               &_FileTransferRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(FileTransferRequest& a, FileTransferRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(FileTransferRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileTransferRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FileTransferRequest* New() const final {
    return CreateMaybeMessage<FileTransferRequest>(nullptr);
  }

  FileTransferRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FileTransferRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FileTransferRequest& from);
  void MergeFrom(const FileTransferRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FileTransferRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "filetransfer.FileTransferRequest";
  }
  protected:
  explicit FileTransferRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_support_2ffiletransfer_5fmessages_2eproto);
    return ::descriptor_table_support_2ffiletransfer_5fmessages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFilenameFieldNumber = 1,
    kFilesizeFieldNumber = 2,
  };
  // string filename = 1;
  void clear_filename();
  const std::string& filename() const;
  void set_filename(const std::string& value);
  void set_filename(std::string&& value);
  void set_filename(const char* value);
  void set_filename(const char* value, size_t size);
  std::string* mutable_filename();
  std::string* release_filename();
  void set_allocated_filename(std::string* filename);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_filename();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_filename(
      std::string* filename);
  private:
  const std::string& _internal_filename() const;
  void _internal_set_filename(const std::string& value);
  std::string* _internal_mutable_filename();
  public:

  // uint64 filesize = 2;
  void clear_filesize();
  ::PROTOBUF_NAMESPACE_ID::uint64 filesize() const;
  void set_filesize(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_filesize() const;
  void _internal_set_filesize(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // @@protoc_insertion_point(class_scope:filetransfer.FileTransferRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filename_;
  ::PROTOBUF_NAMESPACE_ID::uint64 filesize_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_support_2ffiletransfer_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class FileChunk PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:filetransfer.FileChunk) */ {
 public:
  inline FileChunk() : FileChunk(nullptr) {};
  virtual ~FileChunk();

  FileChunk(const FileChunk& from);
  FileChunk(FileChunk&& from) noexcept
    : FileChunk() {
    *this = ::std::move(from);
  }

  inline FileChunk& operator=(const FileChunk& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileChunk& operator=(FileChunk&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FileChunk& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FileChunk* internal_default_instance() {
    return reinterpret_cast<const FileChunk*>(
               &_FileChunk_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(FileChunk& a, FileChunk& b) {
    a.Swap(&b);
  }
  inline void Swap(FileChunk* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileChunk* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FileChunk* New() const final {
    return CreateMaybeMessage<FileChunk>(nullptr);
  }

  FileChunk* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FileChunk>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FileChunk& from);
  void MergeFrom(const FileChunk& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FileChunk* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "filetransfer.FileChunk";
  }
  protected:
  explicit FileChunk(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_support_2ffiletransfer_5fmessages_2eproto);
    return ::descriptor_table_support_2ffiletransfer_5fmessages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFilenameFieldNumber = 1,
    kDataFieldNumber = 3,
    kOffsetFieldNumber = 2,
    kIsLastChunkFieldNumber = 4,
  };
  // string filename = 1;
  void clear_filename();
  const std::string& filename() const;
  void set_filename(const std::string& value);
  void set_filename(std::string&& value);
  void set_filename(const char* value);
  void set_filename(const char* value, size_t size);
  std::string* mutable_filename();
  std::string* release_filename();
  void set_allocated_filename(std::string* filename);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_filename();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_filename(
      std::string* filename);
  private:
  const std::string& _internal_filename() const;
  void _internal_set_filename(const std::string& value);
  std::string* _internal_mutable_filename();
  public:

  // bytes data = 3;
  void clear_data();
  const std::string& data() const;
  void set_data(const std::string& value);
  void set_data(std::string&& value);
  void set_data(const char* value);
  void set_data(const void* value, size_t size);
  std::string* mutable_data();
  std::string* release_data();
  void set_allocated_data(std::string* data);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_data();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_data(
      std::string* data);
  private:
  const std::string& _internal_data() const;
  void _internal_set_data(const std::string& value);
  std::string* _internal_mutable_data();
  public:

  // uint64 offset = 2;
  void clear_offset();
  ::PROTOBUF_NAMESPACE_ID::uint64 offset() const;
  void set_offset(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_offset() const;
  void _internal_set_offset(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // bool is_last_chunk = 4;
  void clear_is_last_chunk();
  bool is_last_chunk() const;
  void set_is_last_chunk(bool value);
  private:
  bool _internal_is_last_chunk() const;
  void _internal_set_is_last_chunk(bool value);
  public:

  // @@protoc_insertion_point(class_scope:filetransfer.FileChunk)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filename_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr data_;
  ::PROTOBUF_NAMESPACE_ID::uint64 offset_;
  bool is_last_chunk_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_support_2ffiletransfer_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class FileUploadFinished PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:filetransfer.FileUploadFinished) */ {
 public:
  inline FileUploadFinished() : FileUploadFinished(nullptr) {};
  virtual ~FileUploadFinished();

  FileUploadFinished(const FileUploadFinished& from);
  FileUploadFinished(FileUploadFinished&& from) noexcept
    : FileUploadFinished() {
    *this = ::std::move(from);
  }

  inline FileUploadFinished& operator=(const FileUploadFinished& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileUploadFinished& operator=(FileUploadFinished&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FileUploadFinished& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FileUploadFinished* internal_default_instance() {
    return reinterpret_cast<const FileUploadFinished*>(
               &_FileUploadFinished_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(FileUploadFinished& a, FileUploadFinished& b) {
    a.Swap(&b);
  }
  inline void Swap(FileUploadFinished* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileUploadFinished* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FileUploadFinished* New() const final {
    return CreateMaybeMessage<FileUploadFinished>(nullptr);
  }

  FileUploadFinished* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FileUploadFinished>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FileUploadFinished& from);
  void MergeFrom(const FileUploadFinished& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FileUploadFinished* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "filetransfer.FileUploadFinished";
  }
  protected:
  explicit FileUploadFinished(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_support_2ffiletransfer_5fmessages_2eproto);
    return ::descriptor_table_support_2ffiletransfer_5fmessages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFilenameFieldNumber = 1,
    kMessageFieldNumber = 2,
  };
  // string filename = 1;
  void clear_filename();
  const std::string& filename() const;
  void set_filename(const std::string& value);
  void set_filename(std::string&& value);
  void set_filename(const char* value);
  void set_filename(const char* value, size_t size);
  std::string* mutable_filename();
  std::string* release_filename();
  void set_allocated_filename(std::string* filename);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_filename();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_filename(
      std::string* filename);
  private:
  const std::string& _internal_filename() const;
  void _internal_set_filename(const std::string& value);
  std::string* _internal_mutable_filename();
  public:

  // string message = 2;
  void clear_message();
  const std::string& message() const;
  void set_message(const std::string& value);
  void set_message(std::string&& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  std::string* mutable_message();
  std::string* release_message();
  void set_allocated_message(std::string* message);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_message();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_message(
      std::string* message);
  private:
  const std::string& _internal_message() const;
  void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // @@protoc_insertion_point(class_scope:filetransfer.FileUploadFinished)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filename_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_support_2ffiletransfer_5fmessages_2eproto;
};
// -------------------------------------------------------------------

class FileUploadStatus PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:filetransfer.FileUploadStatus) */ {
 public:
  inline FileUploadStatus() : FileUploadStatus(nullptr) {};
  virtual ~FileUploadStatus();

  FileUploadStatus(const FileUploadStatus& from);
  FileUploadStatus(FileUploadStatus&& from) noexcept
    : FileUploadStatus() {
    *this = ::std::move(from);
  }

  inline FileUploadStatus& operator=(const FileUploadStatus& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileUploadStatus& operator=(FileUploadStatus&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const FileUploadStatus& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const FileUploadStatus* internal_default_instance() {
    return reinterpret_cast<const FileUploadStatus*>(
               &_FileUploadStatus_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(FileUploadStatus& a, FileUploadStatus& b) {
    a.Swap(&b);
  }
  inline void Swap(FileUploadStatus* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileUploadStatus* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline FileUploadStatus* New() const final {
    return CreateMaybeMessage<FileUploadStatus>(nullptr);
  }

  FileUploadStatus* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<FileUploadStatus>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const FileUploadStatus& from);
  void MergeFrom(const FileUploadStatus& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(FileUploadStatus* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "filetransfer.FileUploadStatus";
  }
  protected:
  explicit FileUploadStatus(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_support_2ffiletransfer_5fmessages_2eproto);
    return ::descriptor_table_support_2ffiletransfer_5fmessages_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFilenameFieldNumber = 1,
    kStatusMessageFieldNumber = 2,
    kBytesReceivedFieldNumber = 4,
    kSuccessFieldNumber = 3,
  };
  // string filename = 1;
  void clear_filename();
  const std::string& filename() const;
  void set_filename(const std::string& value);
  void set_filename(std::string&& value);
  void set_filename(const char* value);
  void set_filename(const char* value, size_t size);
  std::string* mutable_filename();
  std::string* release_filename();
  void set_allocated_filename(std::string* filename);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_filename();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_filename(
      std::string* filename);
  private:
  const std::string& _internal_filename() const;
  void _internal_set_filename(const std::string& value);
  std::string* _internal_mutable_filename();
  public:

  // string status_message = 2;
  void clear_status_message();
  const std::string& status_message() const;
  void set_status_message(const std::string& value);
  void set_status_message(std::string&& value);
  void set_status_message(const char* value);
  void set_status_message(const char* value, size_t size);
  std::string* mutable_status_message();
  std::string* release_status_message();
  void set_allocated_status_message(std::string* status_message);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_status_message();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_status_message(
      std::string* status_message);
  private:
  const std::string& _internal_status_message() const;
  void _internal_set_status_message(const std::string& value);
  std::string* _internal_mutable_status_message();
  public:

  // uint64 bytes_received = 4;
  void clear_bytes_received();
  ::PROTOBUF_NAMESPACE_ID::uint64 bytes_received() const;
  void set_bytes_received(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_bytes_received() const;
  void _internal_set_bytes_received(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // bool success = 3;
  void clear_success();
  bool success() const;
  void set_success(bool value);
  private:
  bool _internal_success() const;
  void _internal_set_success(bool value);
  public:

  // @@protoc_insertion_point(class_scope:filetransfer.FileUploadStatus)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr filename_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr status_message_;
  ::PROTOBUF_NAMESPACE_ID::uint64 bytes_received_;
  bool success_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_support_2ffiletransfer_5fmessages_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ClientMessage

// .filetransfer.FileTransferRequest file_request = 1;
inline bool ClientMessage::_internal_has_file_request() const {
  return content_case() == kFileRequest;
}
inline bool ClientMessage::has_file_request() const {
  return _internal_has_file_request();
}
inline void ClientMessage::set_has_file_request() {
  _oneof_case_[0] = kFileRequest;
}
inline void ClientMessage::clear_file_request() {
  if (_internal_has_file_request()) {
    if (GetArena() == nullptr) {
      delete content_.file_request_;
    }
    clear_has_content();
  }
}
inline ::filetransfer::FileTransferRequest* ClientMessage::release_file_request() {
  // @@protoc_insertion_point(field_release:filetransfer.ClientMessage.file_request)
  if (_internal_has_file_request()) {
    clear_has_content();
      ::filetransfer::FileTransferRequest* temp = content_.file_request_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    content_.file_request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::filetransfer::FileTransferRequest& ClientMessage::_internal_file_request() const {
  return _internal_has_file_request()
      ? *content_.file_request_
      : *reinterpret_cast< ::filetransfer::FileTransferRequest*>(&::filetransfer::_FileTransferRequest_default_instance_);
}
inline const ::filetransfer::FileTransferRequest& ClientMessage::file_request() const {
  // @@protoc_insertion_point(field_get:filetransfer.ClientMessage.file_request)
  return _internal_file_request();
}
inline ::filetransfer::FileTransferRequest* ClientMessage::unsafe_arena_release_file_request() {
  // @@protoc_insertion_point(field_unsafe_arena_release:filetransfer.ClientMessage.file_request)
  if (_internal_has_file_request()) {
    clear_has_content();
    ::filetransfer::FileTransferRequest* temp = content_.file_request_;
    content_.file_request_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ClientMessage::unsafe_arena_set_allocated_file_request(::filetransfer::FileTransferRequest* file_request) {
  clear_content();
  if (file_request) {
    set_has_file_request();
    content_.file_request_ = file_request;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:filetransfer.ClientMessage.file_request)
}
inline ::filetransfer::FileTransferRequest* ClientMessage::_internal_mutable_file_request() {
  if (!_internal_has_file_request()) {
    clear_content();
    set_has_file_request();
    content_.file_request_ = CreateMaybeMessage< ::filetransfer::FileTransferRequest >(GetArena());
  }
  return content_.file_request_;
}
inline ::filetransfer::FileTransferRequest* ClientMessage::mutable_file_request() {
  // @@protoc_insertion_point(field_mutable:filetransfer.ClientMessage.file_request)
  return _internal_mutable_file_request();
}

// .filetransfer.FileChunk file_chunk = 2;
inline bool ClientMessage::_internal_has_file_chunk() const {
  return content_case() == kFileChunk;
}
inline bool ClientMessage::has_file_chunk() const {
  return _internal_has_file_chunk();
}
inline void ClientMessage::set_has_file_chunk() {
  _oneof_case_[0] = kFileChunk;
}
inline void ClientMessage::clear_file_chunk() {
  if (_internal_has_file_chunk()) {
    if (GetArena() == nullptr) {
      delete content_.file_chunk_;
    }
    clear_has_content();
  }
}
inline ::filetransfer::FileChunk* ClientMessage::release_file_chunk() {
  // @@protoc_insertion_point(field_release:filetransfer.ClientMessage.file_chunk)
  if (_internal_has_file_chunk()) {
    clear_has_content();
      ::filetransfer::FileChunk* temp = content_.file_chunk_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    content_.file_chunk_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::filetransfer::FileChunk& ClientMessage::_internal_file_chunk() const {
  return _internal_has_file_chunk()
      ? *content_.file_chunk_
      : *reinterpret_cast< ::filetransfer::FileChunk*>(&::filetransfer::_FileChunk_default_instance_);
}
inline const ::filetransfer::FileChunk& ClientMessage::file_chunk() const {
  // @@protoc_insertion_point(field_get:filetransfer.ClientMessage.file_chunk)
  return _internal_file_chunk();
}
inline ::filetransfer::FileChunk* ClientMessage::unsafe_arena_release_file_chunk() {
  // @@protoc_insertion_point(field_unsafe_arena_release:filetransfer.ClientMessage.file_chunk)
  if (_internal_has_file_chunk()) {
    clear_has_content();
    ::filetransfer::FileChunk* temp = content_.file_chunk_;
    content_.file_chunk_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ClientMessage::unsafe_arena_set_allocated_file_chunk(::filetransfer::FileChunk* file_chunk) {
  clear_content();
  if (file_chunk) {
    set_has_file_chunk();
    content_.file_chunk_ = file_chunk;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:filetransfer.ClientMessage.file_chunk)
}
inline ::filetransfer::FileChunk* ClientMessage::_internal_mutable_file_chunk() {
  if (!_internal_has_file_chunk()) {
    clear_content();
    set_has_file_chunk();
    content_.file_chunk_ = CreateMaybeMessage< ::filetransfer::FileChunk >(GetArena());
  }
  return content_.file_chunk_;
}
inline ::filetransfer::FileChunk* ClientMessage::mutable_file_chunk() {
  // @@protoc_insertion_point(field_mutable:filetransfer.ClientMessage.file_chunk)
  return _internal_mutable_file_chunk();
}

// .filetransfer.FileUploadFinished upload_finished = 3;
inline bool ClientMessage::_internal_has_upload_finished() const {
  return content_case() == kUploadFinished;
}
inline bool ClientMessage::has_upload_finished() const {
  return _internal_has_upload_finished();
}
inline void ClientMessage::set_has_upload_finished() {
  _oneof_case_[0] = kUploadFinished;
}
inline void ClientMessage::clear_upload_finished() {
  if (_internal_has_upload_finished()) {
    if (GetArena() == nullptr) {
      delete content_.upload_finished_;
    }
    clear_has_content();
  }
}
inline ::filetransfer::FileUploadFinished* ClientMessage::release_upload_finished() {
  // @@protoc_insertion_point(field_release:filetransfer.ClientMessage.upload_finished)
  if (_internal_has_upload_finished()) {
    clear_has_content();
      ::filetransfer::FileUploadFinished* temp = content_.upload_finished_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    content_.upload_finished_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::filetransfer::FileUploadFinished& ClientMessage::_internal_upload_finished() const {
  return _internal_has_upload_finished()
      ? *content_.upload_finished_
      : *reinterpret_cast< ::filetransfer::FileUploadFinished*>(&::filetransfer::_FileUploadFinished_default_instance_);
}
inline const ::filetransfer::FileUploadFinished& ClientMessage::upload_finished() const {
  // @@protoc_insertion_point(field_get:filetransfer.ClientMessage.upload_finished)
  return _internal_upload_finished();
}
inline ::filetransfer::FileUploadFinished* ClientMessage::unsafe_arena_release_upload_finished() {
  // @@protoc_insertion_point(field_unsafe_arena_release:filetransfer.ClientMessage.upload_finished)
  if (_internal_has_upload_finished()) {
    clear_has_content();
    ::filetransfer::FileUploadFinished* temp = content_.upload_finished_;
    content_.upload_finished_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ClientMessage::unsafe_arena_set_allocated_upload_finished(::filetransfer::FileUploadFinished* upload_finished) {
  clear_content();
  if (upload_finished) {
    set_has_upload_finished();
    content_.upload_finished_ = upload_finished;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:filetransfer.ClientMessage.upload_finished)
}
inline ::filetransfer::FileUploadFinished* ClientMessage::_internal_mutable_upload_finished() {
  if (!_internal_has_upload_finished()) {
    clear_content();
    set_has_upload_finished();
    content_.upload_finished_ = CreateMaybeMessage< ::filetransfer::FileUploadFinished >(GetArena());
  }
  return content_.upload_finished_;
}
inline ::filetransfer::FileUploadFinished* ClientMessage::mutable_upload_finished() {
  // @@protoc_insertion_point(field_mutable:filetransfer.ClientMessage.upload_finished)
  return _internal_mutable_upload_finished();
}

inline bool ClientMessage::has_content() const {
  return content_case() != CONTENT_NOT_SET;
}
inline void ClientMessage::clear_has_content() {
  _oneof_case_[0] = CONTENT_NOT_SET;
}
inline ClientMessage::ContentCase ClientMessage::content_case() const {
  return ClientMessage::ContentCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// ServerMessage

// .filetransfer.FileUploadStatus upload_status = 1;
inline bool ServerMessage::_internal_has_upload_status() const {
  return this != internal_default_instance() && upload_status_ != nullptr;
}
inline bool ServerMessage::has_upload_status() const {
  return _internal_has_upload_status();
}
inline void ServerMessage::clear_upload_status() {
  if (GetArena() == nullptr && upload_status_ != nullptr) {
    delete upload_status_;
  }
  upload_status_ = nullptr;
}
inline const ::filetransfer::FileUploadStatus& ServerMessage::_internal_upload_status() const {
  const ::filetransfer::FileUploadStatus* p = upload_status_;
  return p != nullptr ? *p : *reinterpret_cast<const ::filetransfer::FileUploadStatus*>(
      &::filetransfer::_FileUploadStatus_default_instance_);
}
inline const ::filetransfer::FileUploadStatus& ServerMessage::upload_status() const {
  // @@protoc_insertion_point(field_get:filetransfer.ServerMessage.upload_status)
  return _internal_upload_status();
}
inline void ServerMessage::unsafe_arena_set_allocated_upload_status(
    ::filetransfer::FileUploadStatus* upload_status) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(upload_status_);
  }
  upload_status_ = upload_status;
  if (upload_status) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:filetransfer.ServerMessage.upload_status)
}
inline ::filetransfer::FileUploadStatus* ServerMessage::release_upload_status() {
  auto temp = unsafe_arena_release_upload_status();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::filetransfer::FileUploadStatus* ServerMessage::unsafe_arena_release_upload_status() {
  // @@protoc_insertion_point(field_release:filetransfer.ServerMessage.upload_status)
  
  ::filetransfer::FileUploadStatus* temp = upload_status_;
  upload_status_ = nullptr;
  return temp;
}
inline ::filetransfer::FileUploadStatus* ServerMessage::_internal_mutable_upload_status() {
  
  if (upload_status_ == nullptr) {
    auto* p = CreateMaybeMessage<::filetransfer::FileUploadStatus>(GetArena());
    upload_status_ = p;
  }
  return upload_status_;
}
inline ::filetransfer::FileUploadStatus* ServerMessage::mutable_upload_status() {
  // @@protoc_insertion_point(field_mutable:filetransfer.ServerMessage.upload_status)
  return _internal_mutable_upload_status();
}
inline void ServerMessage::set_allocated_upload_status(::filetransfer::FileUploadStatus* upload_status) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete upload_status_;
  }
  if (upload_status) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(upload_status);
    if (message_arena != submessage_arena) {
      upload_status = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, upload_status, submessage_arena);
    }
    
  } else {
    
  }
  upload_status_ = upload_status;
  // @@protoc_insertion_point(field_set_allocated:filetransfer.ServerMessage.upload_status)
}

// -------------------------------------------------------------------

// FileTransferRequest

// string filename = 1;
inline void FileTransferRequest::clear_filename() {
  filename_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& FileTransferRequest::filename() const {
  // @@protoc_insertion_point(field_get:filetransfer.FileTransferRequest.filename)
  return _internal_filename();
}
inline void FileTransferRequest::set_filename(const std::string& value) {
  _internal_set_filename(value);
  // @@protoc_insertion_point(field_set:filetransfer.FileTransferRequest.filename)
}
inline std::string* FileTransferRequest::mutable_filename() {
  // @@protoc_insertion_point(field_mutable:filetransfer.FileTransferRequest.filename)
  return _internal_mutable_filename();
}
inline const std::string& FileTransferRequest::_internal_filename() const {
  return filename_.Get();
}
inline void FileTransferRequest::_internal_set_filename(const std::string& value) {
  
  filename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void FileTransferRequest::set_filename(std::string&& value) {
  
  filename_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:filetransfer.FileTransferRequest.filename)
}
inline void FileTransferRequest::set_filename(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  filename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:filetransfer.FileTransferRequest.filename)
}
inline void FileTransferRequest::set_filename(const char* value,
    size_t size) {
  
  filename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:filetransfer.FileTransferRequest.filename)
}
inline std::string* FileTransferRequest::_internal_mutable_filename() {
  
  return filename_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* FileTransferRequest::release_filename() {
  // @@protoc_insertion_point(field_release:filetransfer.FileTransferRequest.filename)
  return filename_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FileTransferRequest::set_allocated_filename(std::string* filename) {
  if (filename != nullptr) {
    
  } else {
    
  }
  filename_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), filename,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:filetransfer.FileTransferRequest.filename)
}
inline std::string* FileTransferRequest::unsafe_arena_release_filename() {
  // @@protoc_insertion_point(field_unsafe_arena_release:filetransfer.FileTransferRequest.filename)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return filename_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void FileTransferRequest::unsafe_arena_set_allocated_filename(
    std::string* filename) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (filename != nullptr) {
    
  } else {
    
  }
  filename_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      filename, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:filetransfer.FileTransferRequest.filename)
}

// uint64 filesize = 2;
inline void FileTransferRequest::clear_filesize() {
  filesize_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 FileTransferRequest::_internal_filesize() const {
  return filesize_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 FileTransferRequest::filesize() const {
  // @@protoc_insertion_point(field_get:filetransfer.FileTransferRequest.filesize)
  return _internal_filesize();
}
inline void FileTransferRequest::_internal_set_filesize(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  filesize_ = value;
}
inline void FileTransferRequest::set_filesize(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_filesize(value);
  // @@protoc_insertion_point(field_set:filetransfer.FileTransferRequest.filesize)
}

// -------------------------------------------------------------------

// FileChunk

// string filename = 1;
inline void FileChunk::clear_filename() {
  filename_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& FileChunk::filename() const {
  // @@protoc_insertion_point(field_get:filetransfer.FileChunk.filename)
  return _internal_filename();
}
inline void FileChunk::set_filename(const std::string& value) {
  _internal_set_filename(value);
  // @@protoc_insertion_point(field_set:filetransfer.FileChunk.filename)
}
inline std::string* FileChunk::mutable_filename() {
  // @@protoc_insertion_point(field_mutable:filetransfer.FileChunk.filename)
  return _internal_mutable_filename();
}
inline const std::string& FileChunk::_internal_filename() const {
  return filename_.Get();
}
inline void FileChunk::_internal_set_filename(const std::string& value) {
  
  filename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void FileChunk::set_filename(std::string&& value) {
  
  filename_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:filetransfer.FileChunk.filename)
}
inline void FileChunk::set_filename(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  filename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:filetransfer.FileChunk.filename)
}
inline void FileChunk::set_filename(const char* value,
    size_t size) {
  
  filename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:filetransfer.FileChunk.filename)
}
inline std::string* FileChunk::_internal_mutable_filename() {
  
  return filename_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* FileChunk::release_filename() {
  // @@protoc_insertion_point(field_release:filetransfer.FileChunk.filename)
  return filename_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FileChunk::set_allocated_filename(std::string* filename) {
  if (filename != nullptr) {
    
  } else {
    
  }
  filename_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), filename,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:filetransfer.FileChunk.filename)
}
inline std::string* FileChunk::unsafe_arena_release_filename() {
  // @@protoc_insertion_point(field_unsafe_arena_release:filetransfer.FileChunk.filename)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return filename_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void FileChunk::unsafe_arena_set_allocated_filename(
    std::string* filename) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (filename != nullptr) {
    
  } else {
    
  }
  filename_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      filename, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:filetransfer.FileChunk.filename)
}

// uint64 offset = 2;
inline void FileChunk::clear_offset() {
  offset_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 FileChunk::_internal_offset() const {
  return offset_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 FileChunk::offset() const {
  // @@protoc_insertion_point(field_get:filetransfer.FileChunk.offset)
  return _internal_offset();
}
inline void FileChunk::_internal_set_offset(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  offset_ = value;
}
inline void FileChunk::set_offset(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_offset(value);
  // @@protoc_insertion_point(field_set:filetransfer.FileChunk.offset)
}

// bytes data = 3;
inline void FileChunk::clear_data() {
  data_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& FileChunk::data() const {
  // @@protoc_insertion_point(field_get:filetransfer.FileChunk.data)
  return _internal_data();
}
inline void FileChunk::set_data(const std::string& value) {
  _internal_set_data(value);
  // @@protoc_insertion_point(field_set:filetransfer.FileChunk.data)
}
inline std::string* FileChunk::mutable_data() {
  // @@protoc_insertion_point(field_mutable:filetransfer.FileChunk.data)
  return _internal_mutable_data();
}
inline const std::string& FileChunk::_internal_data() const {
  return data_.Get();
}
inline void FileChunk::_internal_set_data(const std::string& value) {
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void FileChunk::set_data(std::string&& value) {
  
  data_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:filetransfer.FileChunk.data)
}
inline void FileChunk::set_data(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:filetransfer.FileChunk.data)
}
inline void FileChunk::set_data(const void* value,
    size_t size) {
  
  data_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:filetransfer.FileChunk.data)
}
inline std::string* FileChunk::_internal_mutable_data() {
  
  return data_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* FileChunk::release_data() {
  // @@protoc_insertion_point(field_release:filetransfer.FileChunk.data)
  return data_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FileChunk::set_allocated_data(std::string* data) {
  if (data != nullptr) {
    
  } else {
    
  }
  data_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), data,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:filetransfer.FileChunk.data)
}
inline std::string* FileChunk::unsafe_arena_release_data() {
  // @@protoc_insertion_point(field_unsafe_arena_release:filetransfer.FileChunk.data)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return data_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void FileChunk::unsafe_arena_set_allocated_data(
    std::string* data) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (data != nullptr) {
    
  } else {
    
  }
  data_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      data, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:filetransfer.FileChunk.data)
}

// bool is_last_chunk = 4;
inline void FileChunk::clear_is_last_chunk() {
  is_last_chunk_ = false;
}
inline bool FileChunk::_internal_is_last_chunk() const {
  return is_last_chunk_;
}
inline bool FileChunk::is_last_chunk() const {
  // @@protoc_insertion_point(field_get:filetransfer.FileChunk.is_last_chunk)
  return _internal_is_last_chunk();
}
inline void FileChunk::_internal_set_is_last_chunk(bool value) {
  
  is_last_chunk_ = value;
}
inline void FileChunk::set_is_last_chunk(bool value) {
  _internal_set_is_last_chunk(value);
  // @@protoc_insertion_point(field_set:filetransfer.FileChunk.is_last_chunk)
}

// -------------------------------------------------------------------

// FileUploadFinished

// string filename = 1;
inline void FileUploadFinished::clear_filename() {
  filename_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& FileUploadFinished::filename() const {
  // @@protoc_insertion_point(field_get:filetransfer.FileUploadFinished.filename)
  return _internal_filename();
}
inline void FileUploadFinished::set_filename(const std::string& value) {
  _internal_set_filename(value);
  // @@protoc_insertion_point(field_set:filetransfer.FileUploadFinished.filename)
}
inline std::string* FileUploadFinished::mutable_filename() {
  // @@protoc_insertion_point(field_mutable:filetransfer.FileUploadFinished.filename)
  return _internal_mutable_filename();
}
inline const std::string& FileUploadFinished::_internal_filename() const {
  return filename_.Get();
}
inline void FileUploadFinished::_internal_set_filename(const std::string& value) {
  
  filename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void FileUploadFinished::set_filename(std::string&& value) {
  
  filename_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:filetransfer.FileUploadFinished.filename)
}
inline void FileUploadFinished::set_filename(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  filename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:filetransfer.FileUploadFinished.filename)
}
inline void FileUploadFinished::set_filename(const char* value,
    size_t size) {
  
  filename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:filetransfer.FileUploadFinished.filename)
}
inline std::string* FileUploadFinished::_internal_mutable_filename() {
  
  return filename_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* FileUploadFinished::release_filename() {
  // @@protoc_insertion_point(field_release:filetransfer.FileUploadFinished.filename)
  return filename_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FileUploadFinished::set_allocated_filename(std::string* filename) {
  if (filename != nullptr) {
    
  } else {
    
  }
  filename_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), filename,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:filetransfer.FileUploadFinished.filename)
}
inline std::string* FileUploadFinished::unsafe_arena_release_filename() {
  // @@protoc_insertion_point(field_unsafe_arena_release:filetransfer.FileUploadFinished.filename)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return filename_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void FileUploadFinished::unsafe_arena_set_allocated_filename(
    std::string* filename) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (filename != nullptr) {
    
  } else {
    
  }
  filename_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      filename, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:filetransfer.FileUploadFinished.filename)
}

// string message = 2;
inline void FileUploadFinished::clear_message() {
  message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& FileUploadFinished::message() const {
  // @@protoc_insertion_point(field_get:filetransfer.FileUploadFinished.message)
  return _internal_message();
}
inline void FileUploadFinished::set_message(const std::string& value) {
  _internal_set_message(value);
  // @@protoc_insertion_point(field_set:filetransfer.FileUploadFinished.message)
}
inline std::string* FileUploadFinished::mutable_message() {
  // @@protoc_insertion_point(field_mutable:filetransfer.FileUploadFinished.message)
  return _internal_mutable_message();
}
inline const std::string& FileUploadFinished::_internal_message() const {
  return message_.Get();
}
inline void FileUploadFinished::_internal_set_message(const std::string& value) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void FileUploadFinished::set_message(std::string&& value) {
  
  message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:filetransfer.FileUploadFinished.message)
}
inline void FileUploadFinished::set_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:filetransfer.FileUploadFinished.message)
}
inline void FileUploadFinished::set_message(const char* value,
    size_t size) {
  
  message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:filetransfer.FileUploadFinished.message)
}
inline std::string* FileUploadFinished::_internal_mutable_message() {
  
  return message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* FileUploadFinished::release_message() {
  // @@protoc_insertion_point(field_release:filetransfer.FileUploadFinished.message)
  return message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FileUploadFinished::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:filetransfer.FileUploadFinished.message)
}
inline std::string* FileUploadFinished::unsafe_arena_release_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:filetransfer.FileUploadFinished.message)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return message_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void FileUploadFinished::unsafe_arena_set_allocated_message(
    std::string* message) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (message != nullptr) {
    
  } else {
    
  }
  message_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      message, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:filetransfer.FileUploadFinished.message)
}

// -------------------------------------------------------------------

// FileUploadStatus

// string filename = 1;
inline void FileUploadStatus::clear_filename() {
  filename_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& FileUploadStatus::filename() const {
  // @@protoc_insertion_point(field_get:filetransfer.FileUploadStatus.filename)
  return _internal_filename();
}
inline void FileUploadStatus::set_filename(const std::string& value) {
  _internal_set_filename(value);
  // @@protoc_insertion_point(field_set:filetransfer.FileUploadStatus.filename)
}
inline std::string* FileUploadStatus::mutable_filename() {
  // @@protoc_insertion_point(field_mutable:filetransfer.FileUploadStatus.filename)
  return _internal_mutable_filename();
}
inline const std::string& FileUploadStatus::_internal_filename() const {
  return filename_.Get();
}
inline void FileUploadStatus::_internal_set_filename(const std::string& value) {
  
  filename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void FileUploadStatus::set_filename(std::string&& value) {
  
  filename_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:filetransfer.FileUploadStatus.filename)
}
inline void FileUploadStatus::set_filename(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  filename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:filetransfer.FileUploadStatus.filename)
}
inline void FileUploadStatus::set_filename(const char* value,
    size_t size) {
  
  filename_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:filetransfer.FileUploadStatus.filename)
}
inline std::string* FileUploadStatus::_internal_mutable_filename() {
  
  return filename_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* FileUploadStatus::release_filename() {
  // @@protoc_insertion_point(field_release:filetransfer.FileUploadStatus.filename)
  return filename_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FileUploadStatus::set_allocated_filename(std::string* filename) {
  if (filename != nullptr) {
    
  } else {
    
  }
  filename_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), filename,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:filetransfer.FileUploadStatus.filename)
}
inline std::string* FileUploadStatus::unsafe_arena_release_filename() {
  // @@protoc_insertion_point(field_unsafe_arena_release:filetransfer.FileUploadStatus.filename)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return filename_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void FileUploadStatus::unsafe_arena_set_allocated_filename(
    std::string* filename) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (filename != nullptr) {
    
  } else {
    
  }
  filename_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      filename, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:filetransfer.FileUploadStatus.filename)
}

// string status_message = 2;
inline void FileUploadStatus::clear_status_message() {
  status_message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& FileUploadStatus::status_message() const {
  // @@protoc_insertion_point(field_get:filetransfer.FileUploadStatus.status_message)
  return _internal_status_message();
}
inline void FileUploadStatus::set_status_message(const std::string& value) {
  _internal_set_status_message(value);
  // @@protoc_insertion_point(field_set:filetransfer.FileUploadStatus.status_message)
}
inline std::string* FileUploadStatus::mutable_status_message() {
  // @@protoc_insertion_point(field_mutable:filetransfer.FileUploadStatus.status_message)
  return _internal_mutable_status_message();
}
inline const std::string& FileUploadStatus::_internal_status_message() const {
  return status_message_.Get();
}
inline void FileUploadStatus::_internal_set_status_message(const std::string& value) {
  
  status_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void FileUploadStatus::set_status_message(std::string&& value) {
  
  status_message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:filetransfer.FileUploadStatus.status_message)
}
inline void FileUploadStatus::set_status_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  status_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:filetransfer.FileUploadStatus.status_message)
}
inline void FileUploadStatus::set_status_message(const char* value,
    size_t size) {
  
  status_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:filetransfer.FileUploadStatus.status_message)
}
inline std::string* FileUploadStatus::_internal_mutable_status_message() {
  
  return status_message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* FileUploadStatus::release_status_message() {
  // @@protoc_insertion_point(field_release:filetransfer.FileUploadStatus.status_message)
  return status_message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void FileUploadStatus::set_allocated_status_message(std::string* status_message) {
  if (status_message != nullptr) {
    
  } else {
    
  }
  status_message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), status_message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:filetransfer.FileUploadStatus.status_message)
}
inline std::string* FileUploadStatus::unsafe_arena_release_status_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:filetransfer.FileUploadStatus.status_message)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return status_message_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void FileUploadStatus::unsafe_arena_set_allocated_status_message(
    std::string* status_message) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (status_message != nullptr) {
    
  } else {
    
  }
  status_message_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      status_message, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:filetransfer.FileUploadStatus.status_message)
}

// bool success = 3;
inline void FileUploadStatus::clear_success() {
  success_ = false;
}
inline bool FileUploadStatus::_internal_success() const {
  return success_;
}
inline bool FileUploadStatus::success() const {
  // @@protoc_insertion_point(field_get:filetransfer.FileUploadStatus.success)
  return _internal_success();
}
inline void FileUploadStatus::_internal_set_success(bool value) {
  
  success_ = value;
}
inline void FileUploadStatus::set_success(bool value) {
  _internal_set_success(value);
  // @@protoc_insertion_point(field_set:filetransfer.FileUploadStatus.success)
}

// uint64 bytes_received = 4;
inline void FileUploadStatus::clear_bytes_received() {
  bytes_received_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 FileUploadStatus::_internal_bytes_received() const {
  return bytes_received_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 FileUploadStatus::bytes_received() const {
  // @@protoc_insertion_point(field_get:filetransfer.FileUploadStatus.bytes_received)
  return _internal_bytes_received();
}
inline void FileUploadStatus::_internal_set_bytes_received(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  bytes_received_ = value;
}
inline void FileUploadStatus::set_bytes_received(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_bytes_received(value);
  // @@protoc_insertion_point(field_set:filetransfer.FileUploadStatus.bytes_received)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace filetransfer

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_support_2ffiletransfer_5fmessages_2eproto
